BEGIN;

CREATE TABLE "surveys_survey" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "description" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE "surveys_question" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "type" varchar(20) NOT NULL,
    "text" varchar(500) NOT NULL,
    "description" varchar(500) NOT NULL,
    "required" boolean NOT NULL,
    "order" integer NOT NULL CHECK ("order" >= 0),
    "file_format" varchar(20) NOT NULL,
    "max_file_size_mb" integer NOT NULL CHECK ("max_file_size_mb" >= 0),
    "file_multiple" boolean NOT NULL,
    "survey_id" bigint NOT NULL REFERENCES "surveys_survey"("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "surveys_option" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "value" varchar(100) NOT NULL,
    "label" varchar(255) NOT NULL,
    "order" integer NOT NULL CHECK ("order" >= 0),
    "question_id" bigint NOT NULL REFERENCES "surveys_question"("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "surveys_option_question_id_value_uniq" UNIQUE ("question_id", "value")
);

CREATE TABLE "surveys_response" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "full_name" varchar(255) NOT NULL,
    "email_address" varchar(254) NOT NULL,
    "submitted_at" timestamp with time zone NOT NULL,
    "survey_id" bigint NOT NULL REFERENCES "surveys_survey"("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "surveys_answer" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "value" text NOT NULL,
    "question_id" bigint NOT NULL REFERENCES "surveys_question"("id") DEFERRABLE INITIALLY DEFERRED,
    "response_id" bigint NOT NULL REFERENCES "surveys_response"("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "surveys_answer_response_id_question_id_uniq" UNIQUE ("response_id", "question_id")
);

CREATE TABLE "surveys_certificate" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "file" varchar(100) NOT NULL,
    "original_filename" varchar(255) NOT NULL,
    "uploaded_at" timestamp with time zone NOT NULL,
    "answer_id" bigint NOT NULL REFERENCES "surveys_answer"("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "surveys_question_survey_id_idx" ON "surveys_question" ("survey_id");
CREATE INDEX "surveys_question_name_idx" ON "surveys_question" ("name");
CREATE INDEX "surveys_option_question_id_idx" ON "surveys_option" ("question_id");
CREATE INDEX "surveys_response_survey_id_idx" ON "surveys_response" ("survey_id");
CREATE INDEX "surveys_answer_question_id_idx" ON "surveys_answer" ("question_id");
CREATE INDEX "surveys_answer_response_id_idx" ON "surveys_answer" ("response_id");
CREATE INDEX "surveys_certificate_answer_id_idx" ON "surveys_certificate" ("answer_id");

COMMIT;